[profile.default]
src = "src"
out = 'foundry-out'
libs = ["lib"]
via_ir = true
optimizer_runs = 20_000
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./test/bin/" },
]
solc_version = '0.8.26'
evm_version = "cancun"
bytecode_hash = "none"

# ref: https://github.com/foundry-rs/foundry/issues/4060 otherwise verification will have an issue
auto_detect_remappings = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
